### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by olexandr-konovalov** [dolphin-acoustics-vip/artwarp#1]
Check that the README is up-to-date, has basic usage instructions, dependencies, and describes the purpose of main files. This is what else should be there:
- [x] Authors
- [x] Website (or Wiki to start with)
- [x] Support contacts (e.g. issue tracker)
- [x] GitHub repository
- [x] Some key publications describing it

**Comment by alex-konovalov** [comment]
The first step could be to add details from https://synergy.st-andrews.ac.uk/soundanalysis/ - for a new contributor, this may be a useful exercise to practice the workflow for commits and pull-requests.

**Comment by alex-konovalov** [comment]
It's reopened it, since we did not resolve it completely

**Comment by alex-konovalov** [comment]
This would be still nice to address. As a new contributor to ARTWarp, I don't find it telling me efficiently where to start. Also, extending the README is a good first issue, to practice commits and/or pull requests with some small changes which obviously don't introduce errors in the code.

In addition, we also can have Wiki pages at https://github.com/vmjanik/artwarp/wiki. A start at the Wiki pages could be something what may eventually evolve into a proper documentation.

**Comment by alex-konovalov** [comment]
After migration, wiki is now at https://github.com/dolphin-acoustics-vip/artwarp/wiki. Text there may be easier to edit, and when it stabilises, part or all of it may be transferred to README.

**Comment by olexandr-konovalov** [comment]
Done now - so the only thing needed for the #26 (release) is #7 (license).
