### ISSUE TITLE
Publish a 1st proper release of ARTwarp

### ISSUE THREAD

**Issue by olexandr-konovalov** [dolphin-acoustics-vip/artwarp#26]
We would like to publish a fixed version of the code (and make this a standard practice for next releases). These versions will be available from https://github.com/dolphin-acoustics-vip/artwarp/releases, can be linked from our Wiki based homepage at https://github.com/dolphin-acoustics-vip/artwarp/wiki, and can be made citable with a proper DOI through archiving them on Zenodo. I have created a Milestone for the 1st published release at https://github.com/dolphin-acoustics-vip/artwarp/milestone/1 and allocated several issues that have to be addressed for it. I hope we can reach it by the end of this semester!

This is the outcome needed to achieve the [1st release milestone](https://github.com/dolphin-acoustics-vip/artwarp/milestone/1).

Its steps:
- [x] create stable-1 branch: done https://github.com/dolphin-acoustics-vip/artwarp/tree/stable-1
- [x] wrap archives for the [releases page](https://github.com/dolphin-acoustics-vip/artwarp/releases): done https://github.com/dolphin-acoustics-vip/artwarp/releases/tag/v1.0
- [x] Put download links on [ARTwarp Wiki](https://github.com/dolphin-acoustics-vip/artwarp/wiki)
- [x] Publish release on Zenodo (instructions at https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content): done at https://doi.org/10.5281/zenodo.7713614
- [x] Add Zenodo badge to the README file

**Comment by alex-konovalov** [comment]
P.S. While all the other current issues for the 1st release milestone are about documentation, we need to also agree whether we release the current codebase, or make any modifications.

**Comment by olexandr-konovalov** [comment]
@vmjanik @vdeecke this is done! Please see all links at the checklist above!
